spring:
  application:
    name: api_dev_task

  datasource:
    url: jdbc:mysql://localhost:3306/todo_app_db
    username: myapp_user
    password: myapp_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
  api-docs:
    path: /api-docs

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

logging:
  level:
    com.task.api_dev_task.security: DEBUG
    org.springframework.security: DEBUG
